#!/usr/bin/env npx tsx
/**
 * AI-enriched data pipeline — fetches contracts and spending trends,
 * generates plain-English summaries via Claude Haiku, and writes
 * enriched data files to src/data/.
 *
 * Usage:
 *   npm run enrich -- --dry-run
 *   npm run enrich -- --contracts-only
 *   npm run enrich -- --trends-only
 *   npm run enrich -- --force
 */

import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config(); // .env as fallback
import * as fs from "fs";
import * as path from "path";
import { fetchRecentContracts, fetchSpendingTrends } from "./lib/data-fetcher";
import {
  enrichContractDescription,
  enrichSpendingAnomaly,
  enrichOutcomeCallout,
  delay,
} from "./lib/ai-enricher";
import type { EnrichedContract } from "../src/data/enriched-contracts";
import type { EnrichedTrend } from "../src/data/enriched-trends";
import type {
  InternationalOutcomes,
  OutcomeCallout,
} from "../src/data/international-outcomes";

const ENRICHED_CONTRACTS_PATH = path.resolve(__dirname, "../src/data/enriched-contracts.ts");
const ENRICHED_TRENDS_PATH = path.resolve(__dirname, "../src/data/enriched-trends.ts");
const SUMMARY_PATH = path.resolve(__dirname, "../.enrichment-summary.md");
const OUTCOMES_PATH = path.resolve(__dirname, "../src/data/international-outcomes.json");
const INTL_PATH = path.resolve(__dirname, "../src/data/international.json");

const MAX_ENRICHMENTS_PER_RUN = 50;

/** Maps budget category IDs to the indicator keys that inform their callouts. */
const CATEGORY_INDICATORS: Record<string, { name: string; keys: string[] }> = {
  healthcare: { name: "Healthcare", keys: ["life_expectancy", "infant_mortality", "out_of_pocket_health"] },
  education: { name: "Education", keys: ["education_spending_gdp", "tertiary_enrollment"] },
  "income-security": { name: "Income Security", keys: ["gini_index", "poverty_rate", "income_share_bottom_20"] },
  "social-security": { name: "Social Security", keys: ["social_insurance_coverage"] },
  infrastructure: { name: "Infrastructure", keys: ["broadband_per_100"] },
  defense: { name: "Defense", keys: ["military_spending_gdp"] },
  science: { name: "Science & R&D", keys: ["rd_spending_gdp"] },
};

const STALENESS_THRESHOLD = 0.05;

interface Options {
  dryRun: boolean;
  contractsOnly: boolean;
  trendsOnly: boolean;
  outcomesOnly: boolean;
  force: boolean;
}

function parseArgs(): Options {
  const args = process.argv.slice(2);
  const opts: Options = {
    dryRun: false,
    contractsOnly: false,
    trendsOnly: false,
    outcomesOnly: false,
    force: false,
  };

  for (const arg of args) {
    switch (arg) {
      case "--dry-run":
        opts.dryRun = true;
        break;
      case "--contracts-only":
        opts.contractsOnly = true;
        break;
      case "--trends-only":
        opts.trendsOnly = true;
        break;
      case "--outcomes-only":
        opts.outcomesOnly = true;
        break;
      case "--force":
        opts.force = true;
        break;
    }
  }

  return opts;
}

function loadExistingContracts(): Record<string, EnrichedContract> {
  try {
    const content = fs.readFileSync(ENRICHED_CONTRACTS_PATH, "utf-8");
    const match = content.match(/export const enrichedContracts[^=]*=\s*(\{[\s\S]*\});?\s*$/);
    if (match) {
      // Use Function constructor to evaluate the object literal safely
      return new Function(`return ${match[1]}`)() as Record<string, EnrichedContract>;
    }
  } catch { /* file doesn't exist or is empty */ }
  return {};
}

function loadExistingTrends(): Record<string, EnrichedTrend> {
  try {
    const content = fs.readFileSync(ENRICHED_TRENDS_PATH, "utf-8");
    const match = content.match(/export const enrichedTrends[^=]*=\s*(\{[\s\S]*\});?\s*$/);
    if (match) {
      return new Function(`return ${match[1]}`)() as Record<string, EnrichedTrend>;
    }
  } catch { /* file doesn't exist or is empty */ }
  return {};
}

function writeContractsFile(contracts: Record<string, EnrichedContract>): void {
  const entries = Object.entries(contracts)
    .map(([key, val]) => `  ${JSON.stringify(key)}: ${JSON.stringify(val)}`)
    .join(",\n");

  const content = `/**
 * AI-enriched contract descriptions.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a USASpending award ID to a plain-English summary
 * of the contract, generated by Claude Haiku.
 */

export interface EnrichedContract {
  /** USASpending generated_internal_id — join key to live API data */
  awardId: string;
  /** Original raw description from USASpending */
  rawDescription: string;
  /** AI-generated plain-English summary (1-2 sentences) */
  summary: string;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by awardId for O(1) lookup */
export const enrichedContracts: Record<string, EnrichedContract> = {
${entries}
};
`;

  fs.writeFileSync(ENRICHED_CONTRACTS_PATH, content);
}

function writeTrendsFile(trends: Record<string, EnrichedTrend>): void {
  const entries = Object.entries(trends)
    .map(([key, val]) => `  ${JSON.stringify(key)}: ${JSON.stringify(val)}`)
    .join(",\n");

  const content = `/**
 * AI-enriched spending trend explanations.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a Treasury MTS classification to a "why it matters"
 * explanation, generated by Claude Haiku.
 */

export interface EnrichedTrend {
  /** MTS classification description — join key */
  classification: string;
  /** AI-generated "why it matters" explanation (1-2 sentences) */
  whyItMatters: string;
  /** The change percent at time of enrichment, for staleness detection */
  changePercentAtEnrichment: number;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by classification for O(1) lookup */
export const enrichedTrends: Record<string, EnrichedTrend> = {
${entries}
};
`;

  fs.writeFileSync(ENRICHED_TRENDS_PATH, content);
}

async function main() {
  const opts = parseArgs();
  const apiKey = process.env.ANTHROPIC_API_KEY ?? "";

  console.log("AI Data Enrichment Pipeline");
  console.log("===========================");
  if (opts.dryRun) console.log("Mode: dry run");
  if (opts.contractsOnly) console.log("Scope: contracts only");
  if (opts.trendsOnly) console.log("Scope: trends only");
  if (opts.outcomesOnly) console.log("Scope: outcomes only");
  if (opts.force) console.log("Force: re-enriching all items");
  console.log("");

  if (!apiKey && !opts.dryRun) {
    console.error("ANTHROPIC_API_KEY is required. Set it in .env or environment.");
    process.exit(1);
  }

  const stats = {
    contractsEnriched: 0,
    contractsSkipped: 0,
    contractsPruned: 0,
    trendsEnriched: 0,
    trendsSkipped: 0,
    trendsPruned: 0,
    errors: 0,
  };

  let totalApiCalls = 0;
  const today = new Date().toISOString().split("T")[0];

  // --- Contracts ---
  const updatedContracts: Record<string, EnrichedContract> = {};

  if (!opts.outcomesOnly && !opts.trendsOnly) {
    console.log("--- Contracts ---");
    const existing = loadExistingContracts();
    const rawContracts = await fetchRecentContracts();

    const activeIds = new Set(rawContracts.map((c) => c.awardId));

    // Prune stale entries
    for (const key of Object.keys(existing)) {
      if (activeIds.has(key)) {
        updatedContracts[key] = existing[key];
      } else {
        stats.contractsPruned++;
      }
    }

    for (const contract of rawContracts) {
      if (totalApiCalls >= MAX_ENRICHMENTS_PER_RUN) {
        console.log("  Hit max enrichments per run, stopping contracts.");
        break;
      }

      const existingEntry = updatedContracts[contract.awardId];

      // Skip if already enriched and description hasn't changed (unless forced)
      if (
        existingEntry &&
        existingEntry.rawDescription === contract.description &&
        !opts.force
      ) {
        stats.contractsSkipped++;
        continue;
      }

      if (opts.dryRun) {
        console.log(`  Would enrich: ${contract.recipientName} — ${contract.description.slice(0, 60)}...`);
        stats.contractsEnriched++;
        continue;
      }

      console.log(`  Enriching: ${contract.recipientName}...`);
      const agency = contract.fundingAgency || contract.awardingAgency;
      const summary = await enrichContractDescription(
        contract.description,
        contract.recipientName,
        agency,
        apiKey,
      );

      if (summary === contract.description) {
        stats.errors++;
      } else {
        stats.contractsEnriched++;
      }

      updatedContracts[contract.awardId] = {
        awardId: contract.awardId,
        rawDescription: contract.description,
        summary,
        enrichedAt: today,
      };

      totalApiCalls++;
      await delay(200); // rate limiting
    }

    if (!opts.dryRun) {
      writeContractsFile(updatedContracts);
      console.log(`  Wrote ${Object.keys(updatedContracts).length} entries to enriched-contracts.ts`);
    }
    console.log("");
  }

  // --- Spending Trends ---
  const updatedTrends: Record<string, EnrichedTrend> = {};

  if (!opts.outcomesOnly && !opts.contractsOnly) {
    console.log("--- Spending Trends ---");
    const existing = loadExistingTrends();
    const rawTrends = await fetchSpendingTrends();

    const activeClassifications = new Set(rawTrends.map((t) => t.classification));

    // Prune stale entries
    for (const key of Object.keys(existing)) {
      if (activeClassifications.has(key)) {
        updatedTrends[key] = existing[key];
      } else {
        stats.trendsPruned++;
      }
    }

    for (const trend of rawTrends) {
      if (totalApiCalls >= MAX_ENRICHMENTS_PER_RUN) {
        console.log("  Hit max enrichments per run, stopping trends.");
        break;
      }

      const existingEntry = updatedTrends[trend.classification];

      // Skip if already enriched and change percent hasn't drifted much (unless forced)
      if (
        existingEntry &&
        Math.abs(existingEntry.changePercentAtEnrichment - trend.changePercent) < 5 &&
        !opts.force
      ) {
        stats.trendsSkipped++;
        continue;
      }

      if (opts.dryRun) {
        console.log(`  Would enrich: ${trend.classification} (${trend.changePercent}%)`);
        stats.trendsEnriched++;
        continue;
      }

      console.log(`  Enriching: ${trend.classification} (${trend.changePercent}%)...`);
      const explanation = await enrichSpendingAnomaly(
        trend.classification,
        trend.changePercent,
        trend.currentFytd,
        trend.priorFytd,
        trend.type,
        apiKey,
      );

      if (!explanation) {
        stats.errors++;
        continue;
      }

      stats.trendsEnriched++;
      updatedTrends[trend.classification] = {
        classification: trend.classification,
        whyItMatters: explanation,
        changePercentAtEnrichment: trend.changePercent,
        enrichedAt: today,
      };

      totalApiCalls++;
      await delay(200);
    }

    if (!opts.dryRun) {
      writeTrendsFile(updatedTrends);
      console.log(`  Wrote ${Object.keys(updatedTrends).length} entries to enriched-trends.ts`);
    }
    console.log("");
  }

  // --- Outcome Callouts ---
  if (!opts.contractsOnly && !opts.trendsOnly) {
    console.log("--- Outcome Callouts ---");

    if (!fs.existsSync(OUTCOMES_PATH)) {
      console.log("  No international-outcomes.json found. Run `npm run intl:update` first.");
    } else if (!fs.existsSync(INTL_PATH)) {
      console.log("  No international.json found. Run `npm run intl:update` first.");
    } else {
      const outcomes: InternationalOutcomes = JSON.parse(
        fs.readFileSync(OUTCOMES_PATH, "utf-8")
      );
      const intlData = JSON.parse(fs.readFileSync(INTL_PATH, "utf-8"));
      const existingCallouts = outcomes.callouts ?? {};
      const updatedCallouts: Record<string, Record<string, OutcomeCallout>> = { ...existingCallouts };

      const usIndicators = outcomes.countries.USA?.indicators ?? {};
      const countryCodes = Object.keys(intlData.countries ?? {});

      // US spending ratios from budget.ts FY2025 data ($7,000B total)
      // Cannot import budget.ts directly (uses @/* path aliases)
      const US_RATIOS: Record<string, number> = {
        "social-security": 1540 / 7000,
        healthcare: 1810 / 7000,
        defense: 895 / 7000,
        interest: 952 / 7000,
        "income-security": 660 / 7000,
        veterans: 190 / 7000,
        education: 265 / 7000,
        infrastructure: 175 / 7000,
        immigration: 68 / 7000,
        science: 75 / 7000,
        international: 65 / 7000,
        justice: 82 / 7000,
        agriculture: 42 / 7000,
        government: 181 / 7000,
      };

      let outcomesEnriched = 0;
      let outcomesSkipped = 0;

      for (const [categoryId, catDef] of Object.entries(CATEGORY_INDICATORS)) {
        if (!updatedCallouts[categoryId]) {
          updatedCallouts[categoryId] = {};
        }

        for (const countryCode of countryCodes) {
          if (totalApiCalls >= MAX_ENRICHMENTS_PER_RUN) {
            console.log("  Hit max enrichments per run, stopping outcomes.");
            break;
          }

          const countryOutcomes = outcomes.countries[countryCode];
          if (!countryOutcomes) continue;

          const countryIndicators = countryOutcomes.indicators;

          // Check if we have enough indicators for this category
          const availableKeys = catDef.keys.filter(
            (k) => usIndicators[k] && countryIndicators[k]
          );
          if (availableKeys.length === 0) continue;

          // Staleness check
          const existing = existingCallouts[categoryId]?.[countryCode];
          if (existing && !opts.force) {
            const stale = availableKeys.some((k) => {
              const usKey = `${k}_usa`;
              const countryKey = `${k}_country`;
              const prevUs = existing.indicatorValuesAtEnrichment[usKey];
              const prevCountry = existing.indicatorValuesAtEnrichment[countryKey];
              const currUs = usIndicators[k]?.value;
              const currCountry = countryIndicators[k]?.value;

              if (prevUs == null || prevCountry == null) return true;
              if (currUs == null || currCountry == null) return false;

              const usDrift = Math.abs(currUs - prevUs) / Math.abs(prevUs || 1);
              const countryDrift = Math.abs(currCountry - prevCountry) / Math.abs(prevCountry || 1);
              return usDrift > STALENESS_THRESHOLD || countryDrift > STALENESS_THRESHOLD;
            });

            if (!stale) {
              outcomesSkipped++;
              continue;
            }
          }

          // Format indicators for the prompt
          const countryName = countryOutcomes.name;
          const lines: string[] = [];
          for (const k of availableKeys) {
            const usVal = usIndicators[k];
            const countryVal = countryIndicators[k];
            lines.push(`- ${k.replace(/_/g, " ")}: US ${usVal.value} ${usVal.unit}, ${countryName} ${countryVal.value} ${countryVal.unit}`);
          }

          // Add healthcare system info if healthcare category
          if (categoryId === "healthcare") {
            const usHealth = outcomes.countries.USA?.healthcareSystem;
            const countryHealth = countryOutcomes.healthcareSystem;
            if (usHealth) lines.push(`- Healthcare system: US ${usHealth.type}, coverage ${usHealth.covered}`);
            if (countryHealth) lines.push(`- Healthcare system: ${countryName} ${countryHealth.type}, coverage ${countryHealth.covered}`);
          }

          // Get spending ratios
          const usRatio = US_RATIOS[categoryId] ?? 0;
          const countryRatios = intlData.countries[countryCode]?.ratios ?? {};
          const countryRatio = countryRatios[categoryId] ?? 0;

          if (opts.dryRun) {
            console.log(`  Would enrich: ${catDef.name} × ${countryName}`);
            outcomesEnriched++;
            continue;
          }

          console.log(`  Enriching: ${catDef.name} × ${countryName}...`);
          const calloutText = await enrichOutcomeCallout(
            catDef.name,
            countryName,
            usRatio,
            countryRatio,
            lines.join("\n"),
            apiKey,
          );

          if (!calloutText) {
            stats.errors++;
            continue;
          }

          // Build staleness snapshot
          const snapshot: Record<string, number> = {};
          for (const k of availableKeys) {
            snapshot[`${k}_usa`] = usIndicators[k].value;
            snapshot[`${k}_country`] = countryIndicators[k].value;
          }

          updatedCallouts[categoryId][countryCode] = {
            text: calloutText,
            indicatorValuesAtEnrichment: snapshot,
            enrichedAt: today,
          };

          outcomesEnriched++;
          totalApiCalls++;
          await delay(200);
        }
      }

      if (!opts.dryRun) {
        outcomes.callouts = updatedCallouts;
        outcomes.lastUpdated = today;
        fs.writeFileSync(OUTCOMES_PATH, JSON.stringify(outcomes, null, 2) + "\n");
        console.log(`  Wrote callouts to international-outcomes.json`);
      }

      console.log(`  Outcomes: ${outcomesEnriched} enriched, ${outcomesSkipped} skipped (not stale)`);
      console.log("");
    }
  }

  // --- Summary ---
  console.log("--- Summary ---");
  console.log(`Contracts: ${stats.contractsEnriched} enriched, ${stats.contractsSkipped} skipped, ${stats.contractsPruned} pruned`);
  console.log(`Trends: ${stats.trendsEnriched} enriched, ${stats.trendsSkipped} skipped, ${stats.trendsPruned} pruned`);
  console.log(`Errors: ${stats.errors}`);
  console.log(`Total API calls: ${totalApiCalls}`);

  // Write PR summary
  if (!opts.dryRun && (stats.contractsEnriched > 0 || stats.trendsEnriched > 0)) {
    const summary = `## AI Data Enrichment

| Metric | Count |
|--------|-------|
| Contracts enriched | ${stats.contractsEnriched} |
| Contracts skipped (unchanged) | ${stats.contractsSkipped} |
| Contracts pruned (stale) | ${stats.contractsPruned} |
| Trends enriched | ${stats.trendsEnriched} |
| Trends skipped (unchanged) | ${stats.trendsSkipped} |
| Trends pruned (stale) | ${stats.trendsPruned} |
| Errors | ${stats.errors} |
| Total API calls | ${totalApiCalls} |

### Checklist

- [ ] Review enriched contract summaries for accuracy
- [ ] Review spending trend explanations for accuracy
- [ ] Run \`npm run build\` to verify no type errors
`;
    fs.writeFileSync(SUMMARY_PATH, summary);
    console.log("Wrote PR summary to .enrichment-summary.md");
  }
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
