#!/usr/bin/env npx tsx
/**
 * AI-enriched data pipeline — fetches contracts and spending trends,
 * generates plain-English summaries via Claude Haiku, and writes
 * enriched data files to src/data/.
 *
 * Usage:
 *   npm run enrich -- --dry-run
 *   npm run enrich -- --contracts-only
 *   npm run enrich -- --trends-only
 *   npm run enrich -- --force
 */

import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config(); // .env as fallback
import * as fs from "fs";
import * as path from "path";
import { fetchRecentContracts, fetchSpendingTrends } from "./lib/data-fetcher";
import {
  enrichContractDescription,
  enrichSpendingAnomaly,
  delay,
} from "./lib/ai-enricher";
import type { EnrichedContract } from "../src/data/enriched-contracts";
import type { EnrichedTrend } from "../src/data/enriched-trends";

const ENRICHED_CONTRACTS_PATH = path.resolve(__dirname, "../src/data/enriched-contracts.ts");
const ENRICHED_TRENDS_PATH = path.resolve(__dirname, "../src/data/enriched-trends.ts");
const SUMMARY_PATH = path.resolve(__dirname, "../.enrichment-summary.md");

const MAX_ENRICHMENTS_PER_RUN = 50;

interface Options {
  dryRun: boolean;
  contractsOnly: boolean;
  trendsOnly: boolean;
  force: boolean;
}

function parseArgs(): Options {
  const args = process.argv.slice(2);
  const opts: Options = {
    dryRun: false,
    contractsOnly: false,
    trendsOnly: false,
    force: false,
  };

  for (const arg of args) {
    switch (arg) {
      case "--dry-run":
        opts.dryRun = true;
        break;
      case "--contracts-only":
        opts.contractsOnly = true;
        break;
      case "--trends-only":
        opts.trendsOnly = true;
        break;
      case "--force":
        opts.force = true;
        break;
    }
  }

  return opts;
}

function loadExistingContracts(): Record<string, EnrichedContract> {
  try {
    const content = fs.readFileSync(ENRICHED_CONTRACTS_PATH, "utf-8");
    const match = content.match(/export const enrichedContracts[^=]*=\s*(\{[\s\S]*\});?\s*$/);
    if (match) {
      // Use Function constructor to evaluate the object literal safely
      return new Function(`return ${match[1]}`)() as Record<string, EnrichedContract>;
    }
  } catch { /* file doesn't exist or is empty */ }
  return {};
}

function loadExistingTrends(): Record<string, EnrichedTrend> {
  try {
    const content = fs.readFileSync(ENRICHED_TRENDS_PATH, "utf-8");
    const match = content.match(/export const enrichedTrends[^=]*=\s*(\{[\s\S]*\});?\s*$/);
    if (match) {
      return new Function(`return ${match[1]}`)() as Record<string, EnrichedTrend>;
    }
  } catch { /* file doesn't exist or is empty */ }
  return {};
}

function writeContractsFile(contracts: Record<string, EnrichedContract>): void {
  const entries = Object.entries(contracts)
    .map(([key, val]) => `  ${JSON.stringify(key)}: ${JSON.stringify(val)}`)
    .join(",\n");

  const content = `/**
 * AI-enriched contract descriptions.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a USASpending award ID to a plain-English summary
 * of the contract, generated by Claude Haiku.
 */

export interface EnrichedContract {
  /** USASpending generated_internal_id — join key to live API data */
  awardId: string;
  /** Original raw description from USASpending */
  rawDescription: string;
  /** AI-generated plain-English summary (1-2 sentences) */
  summary: string;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by awardId for O(1) lookup */
export const enrichedContracts: Record<string, EnrichedContract> = {
${entries}
};
`;

  fs.writeFileSync(ENRICHED_CONTRACTS_PATH, content);
}

function writeTrendsFile(trends: Record<string, EnrichedTrend>): void {
  const entries = Object.entries(trends)
    .map(([key, val]) => `  ${JSON.stringify(key)}: ${JSON.stringify(val)}`)
    .join(",\n");

  const content = `/**
 * AI-enriched spending trend explanations.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a Treasury MTS classification to a "why it matters"
 * explanation, generated by Claude Haiku.
 */

export interface EnrichedTrend {
  /** MTS classification description — join key */
  classification: string;
  /** AI-generated "why it matters" explanation (1-2 sentences) */
  whyItMatters: string;
  /** The change percent at time of enrichment, for staleness detection */
  changePercentAtEnrichment: number;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by classification for O(1) lookup */
export const enrichedTrends: Record<string, EnrichedTrend> = {
${entries}
};
`;

  fs.writeFileSync(ENRICHED_TRENDS_PATH, content);
}

async function main() {
  const opts = parseArgs();
  const apiKey = process.env.ANTHROPIC_API_KEY ?? "";

  console.log("AI Data Enrichment Pipeline");
  console.log("===========================");
  if (opts.dryRun) console.log("Mode: dry run");
  if (opts.contractsOnly) console.log("Scope: contracts only");
  if (opts.trendsOnly) console.log("Scope: trends only");
  if (opts.force) console.log("Force: re-enriching all items");
  console.log("");

  if (!apiKey && !opts.dryRun) {
    console.error("ANTHROPIC_API_KEY is required. Set it in .env or environment.");
    process.exit(1);
  }

  const stats = {
    contractsEnriched: 0,
    contractsSkipped: 0,
    contractsPruned: 0,
    trendsEnriched: 0,
    trendsSkipped: 0,
    trendsPruned: 0,
    errors: 0,
  };

  let totalApiCalls = 0;
  const today = new Date().toISOString().split("T")[0];

  // --- Contracts ---
  let updatedContracts: Record<string, EnrichedContract> = {};

  if (!opts.trendsOnly) {
    console.log("--- Contracts ---");
    const existing = loadExistingContracts();
    const rawContracts = await fetchRecentContracts();

    const activeIds = new Set(rawContracts.map((c) => c.awardId));

    // Prune stale entries
    for (const key of Object.keys(existing)) {
      if (activeIds.has(key)) {
        updatedContracts[key] = existing[key];
      } else {
        stats.contractsPruned++;
      }
    }

    for (const contract of rawContracts) {
      if (totalApiCalls >= MAX_ENRICHMENTS_PER_RUN) {
        console.log("  Hit max enrichments per run, stopping contracts.");
        break;
      }

      const existingEntry = updatedContracts[contract.awardId];

      // Skip if already enriched and description hasn't changed (unless forced)
      if (
        existingEntry &&
        existingEntry.rawDescription === contract.description &&
        !opts.force
      ) {
        stats.contractsSkipped++;
        continue;
      }

      if (opts.dryRun) {
        console.log(`  Would enrich: ${contract.recipientName} — ${contract.description.slice(0, 60)}...`);
        stats.contractsEnriched++;
        continue;
      }

      console.log(`  Enriching: ${contract.recipientName}...`);
      const agency = contract.fundingAgency || contract.awardingAgency;
      const summary = await enrichContractDescription(
        contract.description,
        contract.recipientName,
        agency,
        apiKey,
      );

      if (summary === contract.description) {
        stats.errors++;
      } else {
        stats.contractsEnriched++;
      }

      updatedContracts[contract.awardId] = {
        awardId: contract.awardId,
        rawDescription: contract.description,
        summary,
        enrichedAt: today,
      };

      totalApiCalls++;
      await delay(200); // rate limiting
    }

    if (!opts.dryRun) {
      writeContractsFile(updatedContracts);
      console.log(`  Wrote ${Object.keys(updatedContracts).length} entries to enriched-contracts.ts`);
    }
    console.log("");
  }

  // --- Spending Trends ---
  let updatedTrends: Record<string, EnrichedTrend> = {};

  if (!opts.contractsOnly) {
    console.log("--- Spending Trends ---");
    const existing = loadExistingTrends();
    const rawTrends = await fetchSpendingTrends();

    const activeClassifications = new Set(rawTrends.map((t) => t.classification));

    // Prune stale entries
    for (const key of Object.keys(existing)) {
      if (activeClassifications.has(key)) {
        updatedTrends[key] = existing[key];
      } else {
        stats.trendsPruned++;
      }
    }

    for (const trend of rawTrends) {
      if (totalApiCalls >= MAX_ENRICHMENTS_PER_RUN) {
        console.log("  Hit max enrichments per run, stopping trends.");
        break;
      }

      const existingEntry = updatedTrends[trend.classification];

      // Skip if already enriched and change percent hasn't drifted much (unless forced)
      if (
        existingEntry &&
        Math.abs(existingEntry.changePercentAtEnrichment - trend.changePercent) < 5 &&
        !opts.force
      ) {
        stats.trendsSkipped++;
        continue;
      }

      if (opts.dryRun) {
        console.log(`  Would enrich: ${trend.classification} (${trend.changePercent}%)`);
        stats.trendsEnriched++;
        continue;
      }

      console.log(`  Enriching: ${trend.classification} (${trend.changePercent}%)...`);
      const explanation = await enrichSpendingAnomaly(
        trend.classification,
        trend.changePercent,
        trend.currentFytd,
        trend.priorFytd,
        trend.type,
        apiKey,
      );

      if (!explanation) {
        stats.errors++;
        continue;
      }

      stats.trendsEnriched++;
      updatedTrends[trend.classification] = {
        classification: trend.classification,
        whyItMatters: explanation,
        changePercentAtEnrichment: trend.changePercent,
        enrichedAt: today,
      };

      totalApiCalls++;
      await delay(200);
    }

    if (!opts.dryRun) {
      writeTrendsFile(updatedTrends);
      console.log(`  Wrote ${Object.keys(updatedTrends).length} entries to enriched-trends.ts`);
    }
    console.log("");
  }

  // --- Summary ---
  console.log("--- Summary ---");
  console.log(`Contracts: ${stats.contractsEnriched} enriched, ${stats.contractsSkipped} skipped, ${stats.contractsPruned} pruned`);
  console.log(`Trends: ${stats.trendsEnriched} enriched, ${stats.trendsSkipped} skipped, ${stats.trendsPruned} pruned`);
  console.log(`Errors: ${stats.errors}`);
  console.log(`Total API calls: ${totalApiCalls}`);

  // Write PR summary
  if (!opts.dryRun && (stats.contractsEnriched > 0 || stats.trendsEnriched > 0)) {
    const summary = `## AI Data Enrichment

| Metric | Count |
|--------|-------|
| Contracts enriched | ${stats.contractsEnriched} |
| Contracts skipped (unchanged) | ${stats.contractsSkipped} |
| Contracts pruned (stale) | ${stats.contractsPruned} |
| Trends enriched | ${stats.trendsEnriched} |
| Trends skipped (unchanged) | ${stats.trendsSkipped} |
| Trends pruned (stale) | ${stats.trendsPruned} |
| Errors | ${stats.errors} |
| Total API calls | ${totalApiCalls} |

### Checklist

- [ ] Review enriched contract summaries for accuracy
- [ ] Review spending trend explanations for accuracy
- [ ] Run \`npm run build\` to verify no type errors
`;
    fs.writeFileSync(SUMMARY_PATH, summary);
    console.log("Wrote PR summary to .enrichment-summary.md");
  }
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
