#!/usr/bin/env npx tsx
/**
 * Generate the bioguide → FEC candidate ID mapping from the
 * unitedstates/congress-legislators dataset.
 *
 * This dataset is community-maintained and includes both bioguide IDs
 * and FEC candidate IDs for all current members of Congress.
 *
 * Usage:
 *   npx tsx scripts/update-fec-ids.ts
 *   npx tsx scripts/update-fec-ids.ts --dry-run   # preview without writing
 *   npx tsx scripts/update-fec-ids.ts --audit      # check current map against source of truth
 */

import { writeFileSync, readFileSync, mkdtempSync, unlinkSync } from "fs";
import { resolve, join } from "path";
import { execSync } from "child_process";
import { tmpdir } from "os";

const LEGISLATORS_URL =
  "https://raw.githubusercontent.com/unitedstates/congress-legislators/refs/heads/main/legislators-current.yaml";

function parseArgs(): { dryRun: boolean; audit: boolean } {
  const args = process.argv.slice(2);
  return {
    dryRun: args.includes("--dry-run"),
    audit: args.includes("--audit"),
  };
}

interface Legislator {
  bioguide: string;
  fec: string[];
  name: string;
  chamber: "sen" | "rep";
  state: string;
}

async function fetchLegislators(): Promise<Legislator[]> {
  // Fetch the YAML, then use Python (with PyYAML) to parse it into JSON.
  // This avoids shipping a YAML parser in the TS toolchain.
  const res = await fetch(LEGISLATORS_URL);
  if (!res.ok) throw new Error(`Failed to fetch legislators: ${res.status}`);
  const yamlText = await res.text();

  // Write YAML to a temp file, then run Python to parse it
  const tmpDir = mkdtempSync(join(tmpdir(), "fec-"));
  const yamlPath = join(tmpDir, "legislators.yaml");
  const pyPath = join(tmpDir, "parse.py");
  writeFileSync(yamlPath, yamlText);
  writeFileSync(pyPath, [
    "import yaml, json, sys",
    `data = yaml.safe_load(open(sys.argv[1]))`,
    "result = []",
    "for entry in data:",
    '    ids = entry.get("id", {})',
    '    name = entry.get("name", {})',
    '    terms = entry.get("terms", [])',
    "    if not terms: continue",
    "    last_term = terms[-1]",
    "    result.append({",
    '        "bioguide": ids.get("bioguide", ""),',
    '        "fec": ids.get("fec", []),',
    "        \"name\": name.get(\"official_full\") or (name.get(\"first\", \"\") + \" \" + name.get(\"last\", \"\")),",
    '        "chamber": last_term.get("type", ""),',
    '        "state": last_term.get("state", ""),',
    "    })",
    "json.dump(result, sys.stdout)",
  ].join("\n"));

  const jsonOutput = execSync(`python3 ${pyPath} ${yamlPath}`, {
    encoding: "utf-8",
    maxBuffer: 10 * 1024 * 1024,
  });

  // Clean up temp files
  try { unlinkSync(yamlPath); unlinkSync(pyPath); } catch { /* ignore */ }

  return JSON.parse(jsonOutput) as Legislator[];
}

/**
 * Pick the best FEC ID for a legislator based on their current chamber.
 * Senate IDs start with S, House IDs start with H, Presidential with P.
 */
function pickFecId(fecIds: string[], chamber: "rep" | "sen"): string | null {
  if (fecIds.length === 0) return null;
  const prefix = chamber === "sen" ? "S" : "H";
  // Prefer the ID matching current chamber
  const match = fecIds.find((id) => id.startsWith(prefix));
  if (match) return match;
  // Fallback: first non-presidential ID, then anything
  return fecIds.find((id) => !id.startsWith("P")) ?? fecIds[0];
}

function readExistingMappings(): Record<string, string> {
  try {
    const filePath = resolve(new URL(".", import.meta.url).pathname, "../src/data/fec-candidate-ids.ts");
    const content = readFileSync(filePath, "utf-8");
    const pairs: Record<string, string> = {};
    const regex = /"([^"]+)":\s*"([^"]+)"/g;
    let m;
    while ((m = regex.exec(content)) !== null) {
      pairs[m[1]] = m[2];
    }
    return pairs;
  } catch {
    return {};
  }
}

interface Mapping {
  bioguide: string;
  fecId: string;
  name: string;
  chamber: string;
  state: string;
}

function generateFile(mappings: Mapping[]): string {
  const senateEntries = mappings
    .filter((m) => m.chamber === "sen")
    .sort((a, b) => a.state.localeCompare(b.state) || a.name.localeCompare(b.name));
  const houseEntries = mappings
    .filter((m) => m.chamber === "rep")
    .sort((a, b) => a.state.localeCompare(b.state) || a.name.localeCompare(b.name));

  let out = `/**
 * Static mapping of bioguide ID → FEC candidate ID.
 *
 * Auto-generated by: npx tsx scripts/update-fec-ids.ts
 * Source: github.com/unitedstates/congress-legislators
 *
 * Only includes current members of Congress (119th Congress, 2025–2026).
 * FEC candidate IDs are stable across cycles.
 */

export const FEC_CANDIDATE_IDS: Record<string, string> = {
  // Senate — ${senateEntries.length} members
`;

  for (const e of senateEntries) {
    out += `  "${e.bioguide}": "${e.fecId}",  // ${e.name} (${e.state})\n`;
  }

  out += `\n  // House — ${houseEntries.length} members\n`;

  for (const e of houseEntries) {
    out += `  "${e.bioguide}": "${e.fecId}",  // ${e.name} (${e.state})\n`;
  }

  out += `};\n`;
  return out;
}

async function main() {
  const { dryRun, audit } = parseArgs();

  console.log("Fetching current legislators from unitedstates/congress-legislators...");
  const legislators = await fetchLegislators();
  console.log(`Found ${legislators.length} current legislators\n`);

  const mappings: Mapping[] = [];
  const missing: string[] = [];

  for (const leg of legislators) {
    const fecId = pickFecId(leg.fec, leg.chamber);

    if (!fecId) {
      missing.push(`${leg.bioguide} ${leg.name} (${leg.state})`);
      continue;
    }

    mappings.push({
      bioguide: leg.bioguide.toLowerCase(),
      fecId,
      name: leg.name,
      chamber: leg.chamber,
      state: leg.state,
    });
  }

  const senators = mappings.filter((m) => m.chamber === "sen").length;
  const reps = mappings.filter((m) => m.chamber === "rep").length;
  console.log(`Mapped: ${senators} senators + ${reps} representatives = ${mappings.length} total`);

  if (missing.length > 0) {
    console.log(`\nMissing FEC IDs (${missing.length}):`);
    for (const m of missing) console.log(`  ${m}`);
  }

  if (audit) {
    const existing = readExistingMappings();
    console.log(`\nAudit — existing file has ${Object.keys(existing).length} mappings\n`);

    let wrong = 0;
    let missingFromFile = 0;

    for (const m of mappings) {
      const existingId = existing[m.bioguide];
      if (!existingId) {
        missingFromFile++;
      } else if (existingId !== m.fecId) {
        console.log(`  WRONG: ${m.bioguide} ${m.name} — file has ${existingId}, should be ${m.fecId}`);
        wrong++;
      }
    }

    console.log(`\n  ${wrong} incorrect mappings`);
    console.log(`  ${missingFromFile} missing from file`);
    console.log(`  ${mappings.length - wrong - missingFromFile} correct`);
    return;
  }

  if (dryRun) {
    console.log("\n(dry run — no files will be written)");
    console.log(`Would write ${mappings.length} mappings to src/data/fec-candidate-ids.ts`);
    return;
  }

  // Write the file
  const filePath = resolve(new URL(".", import.meta.url).pathname, "../src/data/fec-candidate-ids.ts");
  const content = generateFile(mappings);
  writeFileSync(filePath, content, "utf-8");
  console.log(`\nWrote ${mappings.length} mappings to src/data/fec-candidate-ids.ts`);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
