#!/usr/bin/env npx tsx
/**
 * Fetch OMB budget data and generate TypeScript config for a new fiscal year.
 *
 * Usage:
 *   npm run budget:update -- --year 2026
 *   npm run budget:update -- --year 2026 --file ./local.xlsx
 *   npm run budget:update -- --year 2026 --summary
 *   npm run budget:update -- --year 2026 --json
 *   npm run budget:validate -- --year 2025
 */

import * as fs from "fs";
import * as path from "path";
import { fetchOmbWorkbook, parseOmbTable32 } from "./lib/omb-parser";
import { mapOmbToCategories, type MappedBudgetData } from "./lib/budget-mapper";
import { validateBudgetData } from "./lib/budget-validator";
import {
  getBudgetData,
  TOTAL_FEDERAL_SPENDING,
  type BudgetCategory,
} from "../src/data/budget";

interface Args {
  year: number;
  file?: string;
  json: boolean;
  summary: boolean;
  validate: boolean;
}

function parseArgs(): Args {
  const args = process.argv.slice(2);
  let year = 0;
  let file: string | undefined;
  let json = false;
  let summary = false;
  let validate = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--year" && args[i + 1]) {
      year = parseInt(args[i + 1], 10);
      if (isNaN(year) || year < 2000 || year > 2040) {
        console.error("Error: --year must be a number between 2000 and 2040");
        process.exit(1);
      }
      i++;
    } else if (args[i] === "--file" && args[i + 1]) {
      file = args[i + 1];
      if (!fs.existsSync(file)) {
        console.error(`Error: file not found: ${file}`);
        process.exit(1);
      }
      i++;
    } else if (args[i] === "--json") {
      json = true;
    } else if (args[i] === "--summary") {
      summary = true;
    } else if (args[i] === "--validate") {
      validate = true;
    }
  }

  if (!year) {
    console.error(
      "Usage: npm run budget:update -- --year YYYY [--file ./local.xlsx] [--json] [--summary]"
    );
    console.error(
      "       npm run budget:validate -- --year YYYY"
    );
    process.exit(1);
  }

  return { year, file, json, summary, validate };
}

/**
 * Load prior year budget data from budget.ts for comparison and scaling.
 */
function loadPriorYearData(year: number): {
  categories: BudgetCategory[];
  total: number;
  amounts: Record<string, number>;
} | null {
  // Try the year before the requested one
  const priorYear = year - 1;
  const supportedYears = Object.keys(TOTAL_FEDERAL_SPENDING).map(Number);

  if (!supportedYears.includes(priorYear)) {
    // Fall back to the most recent supported year
    const latest = Math.max(...supportedYears);
    if (latest >= 2024) {
      const categories = getBudgetData(latest as 2024 | 2025);
      const total = TOTAL_FEDERAL_SPENDING[latest as keyof typeof TOTAL_FEDERAL_SPENDING];
      const amounts: Record<string, number> = {};
      for (const cat of categories) {
        amounts[cat.id] = cat.amount;
      }
      return { categories, total, amounts };
    }
    return null;
  }

  const categories = getBudgetData(priorYear as 2024 | 2025);
  const total = TOTAL_FEDERAL_SPENDING[priorYear as keyof typeof TOTAL_FEDERAL_SPENDING];
  const amounts: Record<string, number> = {};
  for (const cat of categories) {
    amounts[cat.id] = cat.amount;
  }
  return { categories, total, amounts };
}

/**
 * Generate TypeScript output file contents.
 */
function generateTypeScript(data: MappedBudgetData): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * FY${data.year} budget data — generated by budget:update`);
  lines.push(` * Source: OMB Historical Table 3.2`);
  lines.push(` * Generated: ${new Date().toISOString().split("T")[0]}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`// Total federal spending (billions)`);
  lines.push(
    `export const FY${data.year}_TOTAL_SPENDING = ${data.totalSpending};`
  );
  lines.push(``);
  lines.push(`// Category amounts (billions)`);
  lines.push(
    `export const FY${data.year}_AMOUNTS: Record<string, number> = {`
  );

  // Sort by amount descending for readability
  const sorted = Object.entries(data.amounts).sort((a, b) => b[1] - a[1]);
  for (const [id, amount] of sorted) {
    lines.push(`  "${id}": ${amount},`);
  }
  lines.push(`};`);
  lines.push(``);

  if (Object.keys(data.subcategoryOverrides).length > 0) {
    lines.push(`// Subcategory overrides (billions)`);
    lines.push(
      `export const FY${data.year}_SUBCATEGORY_OVERRIDES: Record<string, Record<string, number>> = {`
    );

    for (const [categoryId, subs] of Object.entries(
      data.subcategoryOverrides
    )) {
      lines.push(`  "${categoryId}": {`);
      for (const [name, amount] of Object.entries(subs)) {
        lines.push(`    "${name}": ${amount},`);
      }
      lines.push(`  },`);
    }

    lines.push(`};`);
  }

  return lines.join("\n");
}

/**
 * Print a summary table of category amounts with changes.
 */
function printSummaryTable(
  data: MappedBudgetData,
  priorAmounts?: Record<string, number>
) {
  console.log(
    `\n${"Category".padEnd(25)} ${"Amount".padStart(8)} ${priorAmounts ? "Prior".padStart(8) + " Change".padStart(8) : ""}`
  );
  console.log("-".repeat(priorAmounts ? 49 : 33));

  const sorted = Object.entries(data.amounts).sort((a, b) => b[1] - a[1]);
  for (const [id, amount] of sorted) {
    let line = `${id.padEnd(25)} ${("$" + amount + "B").padStart(8)}`;
    if (priorAmounts && priorAmounts[id]) {
      const prior = priorAmounts[id];
      const pct = ((amount - prior) / prior) * 100;
      line += ` ${("$" + prior + "B").padStart(8)} ${(pct >= 0 ? "+" : "") + pct.toFixed(1) + "%"}`.padStart(8);
    }
    console.log(line);
  }

  console.log("-".repeat(priorAmounts ? 49 : 33));
  console.log(
    `${"TOTAL".padEnd(25)} ${("$" + data.totalSpending + "B").padStart(8)}`
  );
}

async function main() {
  const { year, file, json, summary, validate } = parseArgs();

  // Load prior year data
  const priorYear = loadPriorYearData(year);

  // Validate-only mode: check existing data in budget.ts
  if (validate) {
    if (!priorYear) {
      console.error(`No budget data found for year ${year} or prior years.`);
      process.exit(1);
    }

    // Build MappedBudgetData from existing budget.ts data
    const existingData: MappedBudgetData = {
      year,
      totalSpending: Object.values(priorYear.amounts).reduce(
        (a, b) => a + b,
        0
      ),
      amounts: priorYear.amounts,
      subcategoryOverrides: {},
      unmappedRows: [],
      warnings: [],
    };

    // Build subcategory overrides from existing data
    for (const cat of priorYear.categories) {
      const subs: Record<string, number> = {};
      for (const sub of cat.subcategories) {
        subs[sub.name] = sub.amount;
      }
      existingData.subcategoryOverrides[cat.id] = subs;
    }

    const { results, allPassed } = validateBudgetData(existingData);

    console.log(`\nValidation for FY${year} budget data:\n`);
    for (const r of results) {
      console.log(`  ${r.pass ? "✓" : "✗"} ${r.message}`);
    }

    process.exit(allPassed ? 0 : 1);
  }

  // Fetch or read the Excel file
  let source: Buffer | string;

  if (file) {
    if (!json) console.log(`Reading OMB data from ${file}...`);
    source = path.resolve(file);
  } else {
    if (!json) console.log(`Fetching OMB Historical Table 3.2...`);
    source = await fetchOmbWorkbook();
    if (!json) console.log(`Downloaded.`);
  }

  // Parse
  if (!json) console.log(`Parsing FY${year} data...`);
  const parseResult = parseOmbTable32(source, year);

  if (parseResult.warnings.length > 0 && !json) {
    console.log(`\nParse warnings:`);
    for (const w of parseResult.warnings) {
      console.log(`  ⚠ ${w}`);
    }
  }

  // Map to our categories
  const mapped = mapOmbToCategories(parseResult, priorYear?.categories);

  if (mapped.warnings.length > 0 && !json) {
    console.log(`\nMapping warnings:`);
    for (const w of mapped.warnings) {
      console.log(`  ⚠ ${w}`);
    }
  }

  // Validate
  const { results, allPassed } = validateBudgetData(
    mapped,
    priorYear?.total,
    priorYear?.amounts
  );

  if (json) {
    console.log(
      JSON.stringify(
        {
          data: mapped,
          validation: { results, allPassed },
          typescript: generateTypeScript(mapped),
        },
        null,
        2
      )
    );
    return;
  }

  // Print validation
  console.log(`\nValidation:`);
  for (const r of results) {
    console.log(`  ${r.pass ? "✓" : "✗"} ${r.message}`);
  }

  // Print summary table
  if (summary || !json) {
    printSummaryTable(mapped, priorYear?.amounts);
  }

  // Generate output file
  const outputDir = path.resolve(__dirname, "output");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, `fy${year}-budget.ts`);
  const tsContent = generateTypeScript(mapped);
  fs.writeFileSync(outputPath, tsContent + "\n");

  console.log(`\nGenerated: ${outputPath}`);
  console.log(`\nTo apply:`);
  console.log(
    `  1. Copy FY${year}_AMOUNTS into src/data/budget.ts as a new const`
  );
  console.log(
    `  2. Copy FY${year}_SUBCATEGORY_OVERRIDES into src/data/budget.ts`
  );
  console.log(
    `  3. Add ${year}: ${mapped.totalSpending} to TOTAL_FEDERAL_SPENDING`
  );
  console.log(
    `  4. Update TaxYear type and SUPPORTED_TAX_YEARS if adding a new year`
  );
  console.log(`  5. Run \`npm test\` to verify`);

  if (!allPassed) {
    console.log(
      `\n⚠ Some validation checks failed — review the output above before applying.`
    );
  }

  if (mapped.unmappedRows.length > 0) {
    console.log(`\nUnmapped OMB rows (${mapped.unmappedRows.length}):`);
    for (const row of mapped.unmappedRows) {
      console.log(
        `  ${row.functionCode} ${row.functionName}: ${row.amount.toFixed(1)}B`
      );
    }
  }
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
