/**
 * AI-enriched spending trend explanations.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a Treasury MTS classification to a "why it matters"
 * explanation, generated by Claude Haiku.
 */

export interface EnrichedTrend {
  /** MTS classification description — join key */
  classification: string;
  /** AI-generated "why it matters" explanation (1-2 sentences) */
  whyItMatters: string;
  /** The change percent at time of enrichment, for staleness detection */
  changePercentAtEnrichment: number;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by classification for O(1) lookup */
export const enrichedTrends: Record<string, EnrichedTrend> = {
  "Customs Duties": {"classification":"Customs Duties","whyItMatters":"The Trump administration raised tariffs (taxes on imported goods) significantly starting in 2024, which is why customs duties jumped so much compared to last year. This means prices for everyday items like clothes, electronics, and groceries could go up for shoppers since companies often pass these extra costs to customers.","changePercentAtEnrichment":131.7,"enrichedAt":"2026-06-22"},
  "General Government": {"classification":"General Government","whyItMatters":"This drop likely happened because the government spent less on administrative costs, employee salaries, and building maintenance—areas that often get cut when budgets tighten or priorities shift. For taxpayers, this means the government is spending less of your tax dollars on its own operations, which could free up money for other programs, though it might also mean slower government services if too many positions are eliminated.","changePercentAtEnrichment":-32.4,"enrichedAt":"2026-06-22"},
  "Community and Regional Development": {"classification":"Community and Regional Development","whyItMatters":"This big drop likely happened because Congress didn't renew or fully fund major infrastructure and community development programs that expired or were reduced in the budget—possibly including things like local development grants, disaster recovery money, or regional projects that had temporary funding. For taxpayers, this means less federal money flowing to local communities for things like fixing roads, supporting small businesses, or rebuilding after disasters, so states and cities may have to raise local taxes or cut their own programs to fill the gap.","changePercentAtEnrichment":-51.6,"enrichedAt":"2026-06-22"},
  "Natural Resources and Environment": {"classification":"Natural Resources and Environment","whyItMatters":"The biggest reason for this drop is likely the end of major one-time spending from the Inflation Reduction Act and Bipartisan Infrastructure Law, which had boosted environmental and conservation projects in previous years. For taxpayers, this means the government is spending less on things like national parks, pollution cleanup, and renewable energy projects right now, though it may also mean slightly lower pressure on federal budgets in this area.","changePercentAtEnrichment":-39.5,"enrichedAt":"2026-06-22"},
  "Energy": {"classification":"Energy","whyItMatters":"Energy spending dropped mainly because federal investments in renewable energy projects and infrastructure programs wound down after their initial funding phases ended. For taxpayers, this means the government is spending less money on energy-related programs right now, which could slightly reduce the overall federal budget deficit, though it might also slow down some clean energy projects that were underway.","changePercentAtEnrichment":-21.5,"enrichedAt":"2026-06-22"},
  "Corporation Income Taxes": {"classification":"Corporation Income Taxes","whyItMatters":"Corporate profits have dropped significantly, likely due to slower economic growth and higher interest rates making it harder for businesses to earn money, which means the government collects less tax from company earnings. This could eventually lead to higher taxes on individuals or cuts to government services, since the government has less money coming in to pay for programs that taxpayers rely on.","changePercentAtEnrichment":-29.6,"enrichedAt":"2026-06-22"},
  "Administration of Justice": {"classification":"Administration of Justice","whyItMatters":"The increase is likely due to higher costs for federal courts, prisons, and law enforcement agencies dealing with more cases and inflation making everything more expensive. This means taxpayers are paying more in taxes to cover these justice system costs, though the government hasn't necessarily changed the laws—it's just spending more to run the existing system.","changePercentAtEnrichment":23.4,"enrichedAt":"2026-03-15"},
  "Agriculture": {"classification":"Agriculture","whyItMatters":"Farm aid programs and crop insurance payouts jumped significantly this year because of bad weather and low crop prices that hurt farmers across the country. This means taxpayers are paying more money to help farmers stay in business, which could eventually show up as slightly higher taxes or less money available for other government programs.","changePercentAtEnrichment":15.7,"enrichedAt":"2026-06-22"}
};
