/**
 * AI-enriched contract descriptions.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a USASpending award ID to a plain-English summary
 * of the contract, generated by Claude Haiku.
 */

export interface EnrichedContract {
  /** USASpending generated_internal_id — join key to live API data */
  awardId: string;
  /** Original raw description from USASpending */
  rawDescription: string;
  /** AI-generated plain-English summary (1-2 sentences) */
  summary: string;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by awardId for O(1) lookup */
export const enrichedContracts: Record<string, EnrichedContract> = {

};
