/**
 * AI-enriched spending trend explanations.
 * Generated by scripts/enrich-data.ts — do not edit manually.
 *
 * Each entry maps a Treasury MTS classification to a "why it matters"
 * explanation, generated by Claude Haiku.
 */

export interface EnrichedTrend {
  /** MTS classification description — join key */
  classification: string;
  /** AI-generated "why it matters" explanation (1-2 sentences) */
  whyItMatters: string;
  /** The change percent at time of enrichment, for staleness detection */
  changePercentAtEnrichment: number;
  /** ISO date when this enrichment was generated */
  enrichedAt: string;
}

/** Keyed by classification for O(1) lookup */
export const enrichedTrends: Record<string, EnrichedTrend> = {
  "Customs Duties": {"classification":"Customs Duties","whyItMatters":"The Trump administration imposed new tariffs on imports from China and other countries starting in 2024, which means the government collects more money when foreign goods enter the U.S.—that's why customs duties jumped so dramatically. For everyday taxpayers, this means prices on imported products like clothes, electronics, and toys could go up in stores, which effectively acts like a hidden tax on your shopping.","changePercentAtEnrichment":307.6,"enrichedAt":"2026-03-15"},
  "General Government": {"classification":"General Government","whyItMatters":"This unusual swing—from $15.8 billion in spending to negative $5.6 billion—likely reflects accounting adjustments or refunds rather than actual spending cuts, possibly from tax refunds issued or prior-year corrections being recorded as negative spending. For taxpayers, this generally means the government is returning money it previously collected, which doesn't directly change what you owe but does affect how the budget numbers look on paper.","changePercentAtEnrichment":-135.2,"enrichedAt":"2026-03-15"},
  "Community and Regional Development": {"classification":"Community and Regional Development","whyItMatters":"This big drop likely happened because the government finished spending money from emergency pandemic relief programs that were approved in 2021 and 2022, which included lots of funding for community projects and infrastructure. For taxpayers, this means less federal money flowing to local projects like roads, bridges, and community development programs in your area, so your state and local governments may need to find other ways to pay for these improvements or scale back some projects.","changePercentAtEnrichment":-57.6,"enrichedAt":"2026-03-15"},
  "Natural Resources and Environment": {"classification":"Natural Resources and Environment","whyItMatters":"The biggest reason for this drop is likely that last year included major one-time spending from the Inflation Reduction Act, which funded climate and environmental projects, while this year doesn't have that same boost. For taxpayers, this means less federal money is going toward things like protecting national parks, cleaning up pollution, and renewable energy projects right now.","changePercentAtEnrichment":-49.2,"enrichedAt":"2026-03-15"},
  "Energy": {"classification":"Energy","whyItMatters":"The decrease is likely due to the end of major spending programs from the Inflation Reduction Act, which provided a big boost to clean energy projects in the previous year. This means taxpayers are paying less in federal money toward energy programs right now, though it could also mean fewer new solar, wind, and energy efficiency projects getting funded compared to last year.","changePercentAtEnrichment":-29.7,"enrichedAt":"2026-03-15"},
  "International Affairs": {"classification":"International Affairs","whyItMatters":"The decrease is likely due to the end of major emergency aid packages to Ukraine and other countries that were passed in 2023, since those were one-time spending bills rather than permanent programs. For taxpayers, this means the government is spending less money on foreign aid and international programs right now, which could slightly reduce the overall federal budget deficit, though it's a small part of total government spending.","changePercentAtEnrichment":-24.8,"enrichedAt":"2026-03-15"},
  "Corporation Income Taxes": {"classification":"Corporation Income Taxes","whyItMatters":"Corporate profits have dropped significantly, likely due to slower economic growth and higher interest rates making it harder for businesses to earn money, so the government is collecting less tax from company earnings. This means the federal government has less money coming in, which could lead to higher deficits unless spending is cut or other taxes are raised on individuals.","changePercentAtEnrichment":-24.1,"enrichedAt":"2026-03-15"},
  "Administration of Justice": {"classification":"Administration of Justice","whyItMatters":"The increase is likely due to higher costs for federal courts, prisons, and law enforcement agencies dealing with more cases and inflation making everything more expensive. This means taxpayers are paying more in taxes to cover these justice system costs, though the government hasn't necessarily changed the laws—it's just spending more to run the existing system.","changePercentAtEnrichment":23.4,"enrichedAt":"2026-03-15"}
};
